TESTS_ENVIRONMENT += \
 TIMEOUT="$(TIMEOUT)" \
 MKTEMP="$(MKTEMP)"

check_PROGRAMS += \
 tests/create-write-persist-test \
 tests/create-write-persist-remove-test

TESTS += \
 tests/basic.sh \
 tests/copy-to-and-from.sh \
 tests/copy-to-and-from-multi-providers.sh \
 tests/copy-to-and-from-multi-targets.sh \
 tests/create-write-persist.sh \
 tests/create-write-persist-remove.sh \
 tests/basic-file.sh \
 tests/copy-to-and-from-file.sh \
 tests/copy-to-and-from-multi-providers-file.sh \
 tests/copy-to-and-from-multi-targets-file.sh \
 tests/create-write-persist-file.sh \
 tests/create-write-persist-remove-file.sh

EXTRA_DIST += \
 tests/lorem.txt \
 tests/basic.sh \
 tests/copy-to-and-from.sh \
 tests/copy-to-and-from-multi-providers.sh \
 tests/copy-to-and-from-multi-targets.sh \
 tests/create-write-persist.sh \
 tests/create-write-persist-remove.sh

